[package]
name = "quack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
regex = "1.10.1"
termcolor = "1.3.0"
env_logger = "0.10.0"
dirs = "5.0.1"
